name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  firebase_storage:
    path: ../
  firebase_core:
    path: ../../firebase_core/firebase_core
  uuid: ^2.0.2
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
