name: firebase_storage
description: Flutter plugin for Firebase Cloud Storage, a powerful, simple, and
  cost-effective object storage service for Android and iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage
version: 4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.storage
        pluginClass: FirebaseStoragePlugin
      ios:
        pluginClass: FLTFirebaseStoragePlugin
      macos:
        pluginClass: FLTFirebaseStoragePlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0

dev_dependencies:
  firebase_core_platform_interface: ^2.0.0
  pedantic: ^1.8.0
  http: ^0.12.0
  flutter_test:
    sdk: flutter
  uuid: ^2.0.4
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
